# -*- coding: utf-8 -*-
"""soal_1_timeconverter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVbF8sBe8arM5KJJxKm2fGM_-bLg4Zqu
"""

def timeconverter(seconds):                                                     # mendefinisikan fungsi 'timeconverter' dgn 1 parameter
  '''
  Fungsi ini mengkonversi dari nilai detik ke format waktu dua digit:
  
  HH : MM : SS

  H = Hour (jam)
  M = Minute (menit)
  S = Second (detik)

  Program hanya menerima angka bulat, dengan nilai maksimal 359999.
  Jika input bernilai lebih dari 359999, bilangan desimal, bilangan negatif, maupun string, 
  akan keluar pemberitahuan "Invalid Input!"

  '''

  seconds = input('Masukkan detik : ')                                          # assign variable 'seconds' dgn fungsi input string

  if seconds.isdigit() and int(seconds) < 359999:                               # masuk ke kondisi JIKA seluruh karakter dalam komponen input adalah digit DAN nilainya kurang dari 359999,maka penghitungan dilanjutkan
    seconds = int(seconds)                                                      # reassign variable 'seconds' dgn nilai yang sudah terkonversi ke integer data type
    import math                                                                 # import math library untuk menggunakan fungsi 'floor'
    hour = math.floor(seconds/3600)                                             # assign 'hour' dgn penghitungan input 'seconds' dibagi 3600 kemudian melakukan pembulatan ke bawah karena konteks waktu; misal waktu saat ini jam 1,35 menit, maka penyebutan waktu cenderung jam 1 bukan jam 2.
    minute = math.floor((seconds - hour*3600)/60)                               # assign 'minute' dgn penghitungan input 'seconds' dikurang nilai 'hour' yang telah dikali 3600 supaya satuannya sama. kemudian dibagi 60 dari detik ke menit. setelahnya dilakukan pembulatan ke bawah kembali
    seconds = math.floor(seconds - hour*3600 - minute*60)                       # reassign 'seconds' dgn penghitungan input 'seconds' dikurang nilai 'hour' yang telah dikali 3600, dikurangi lagi dgn 'minute' yang telah dikali 60. setelahnya dilakukan pembulatan ke bawah
    return "Konversi : {:02d}:{:02d}:{:02d}".format(hour, minute, seconds)      # return dengan string berformat 2 digit sehingga yang nilai awalnya 1 menjadi 01. berlaku untuk semua variable.

  else: 
    return "Invalid Input!"                                                     # JIKA TIDAK masuk ke kondisi awal, maka akan return string 'invalid input'.
  

print(timeconverter(3600))
print(timeconverter(3665))
print(timeconverter('ujian'))
print(timeconverter(20.5))